# Generated by Django 5.1 on 2024-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
